#server
server:
  port: 8888
spring:
  application:
  name: config-server
# git server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-scs/SpringCloudScaffolding.git
          search-paths: config-repo
          username: 2975153510@qq.com
          password: chay27.!@#
        label: develop
  rabbitmq:
    host: 10.20.2.65
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#actuator  启用所有的监控端点 “*”号代表启用所有的监控端点，可以单独启用，例如，health，info，metrics
#  spring boot 升为 2.0 后，为了安全，默认 Actuator 只暴露了2个端点，heath 和 info
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS